/**
 * Authentication
 */

export const SET_AUTHENTICATED_STATUS = "SET_AUTHENTICATED_STATUS";
export const GET_AUTHENTICATED_STATUS = "GET_AUTHENTICATED_STATUS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

/**
 * Profile
 */
export const SET_PROFILE = "SET_PROFILE";
export const ADD_PICKUP_STUDENT = "ADD_PICKUP_STUDENT";
export const REMOVE_PICKUP_STUDENT = "REMOVE_PICKUP_STUDENT";
export const CHANGE_PICKUP_PLATE = "CHANGE_PICKUP_PLATE";

/**
 * Time Check-in
 */

export const LOAD_CHECKIN_LIST = "LOAD_CHECKIN_LIST";

/**
 * Calendar
 */

export const FETCH_CALENDAR_EVENTS = "FETCH_CALENDAR_EVENTS";
export const ADD_CALENDAR_FAVORITE = "ADD_CALENDAR_FAVORITE";
export const REMOVE_CALENDAR_FAVORITE = "REMOVE_CALENDAR_FAVORITE";
