export const LOAD_PICKUP_LIST = "LOAD_PICKUP_LIST";
export const CREATE_PICKUP_ITEM = "CREATE_PICKUP_ITEM";
export const LOAD_REGISTERED_STUDENT = "LOAD_REGISTERED_STUDENT";
export const REGISTER_NEW_STUDENT = "REGISTER_NEW_STUDENT";
export const DEREGISTER_STUDENT = "DEREGISTER_STUDENT";

export const LOAD_CALENDAR_LIST = "LOAD_CALENDAR_LIST";
export const TOGGLE_CALENDAR_FAVORITE = "TOGGLE_CALENDAR_FAVORITE";
